### PR TITLE
no more protected attributes

### PR DESCRIPTION
**Pull request by grosser**
@bquorning @zendesk/octo 

rails 4.0 has the method defined, so checking for rails 3 or ProtectedAttributes

### Risks
 - None

### CODE REVIEW

**Comment by staugaard** [comment]
:+1: on green

**Comment by grosser** [comment]
jruby also failed on master when triggering a new build: https://github.com/zendesk/property_sets/pull/53

fixed by adding `JRUBY_OPTS=""`

**Comment by pschambacher** [comment]
rails 5.0 won't support this altogether

**Comment by grosser** [comment]
Time to kick it out :)

**Pull request merged**
